[package]
name = "yb_stats"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
port_scanner = "0.1.5"
serde = "1.0.136"
serde_json = "1.0.79"
serde_derive = "1.0.136"
reqwest = { version = "0.11.10", features = ["blocking"] }
itertools = "0.10.3"
regex = "1.5.5"
substring = "1.4.5"
csv = "1.1.6"
chrono = { version = "0.4.19", features = ["serde"] }
rayon = "1.5.1"
scraper = "0.12.0"
dotenv = "0.15.0"